name: Notification PR

on:
  pull_request_target:
    types:
      - opened

jobs:
  notify:
    name: Pull Request Notification
    runs-on: ubuntu-latest
    steps:
      - name: Create Mattermost Message
        # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#example-of-a-script-injection-attack
        env:
          NUMBER: ${{ github.event.number }}
          PR_URL: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
          REPO: ${{ github.repository }}
          USER: ${{ github.actor }}
          TITLE: ${{ github.event.pull_request.title }}
          MM_CHANNEL_NAME: ${{ secrets.MM_CHANNGEL_NAME }}
          BOT_NAME: ${{ secrets.MM_BOT_NAME }}
        run: |
          jq --null-input \
                --arg number "$NUMBER" \
                --arg pr_url "$PR_URL" \
                --arg repo "$REPO" \
                --arg user "$USER" \
                --arg title "$TITLE" \
                --arg channel "$MM_CHANNEL_NAME" \
                --arg name "$BOT_NAME" \
          '{"name": "\($name)", "channel": "\($channel)", "text": "[\($repo)] | [\($title) #\($number)](\($pr_url)) was created by \($user)" }' > mattermost.json

      - name: Notification
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
