name: 'Welcome New Contributors'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write
  issues: write

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: 'Greet the contributor'
        uses: garg3133/welcome-new-contributors@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
              Thank you for opening your first issue, one of our team members will review it as soon as it possible. ❤️🎉
          pr-message: |-
              Thank you for making your first Pull Request and taking the time to improve Koobiq ! ❤️🎉
